[package]
name = "elo-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elo-lexer = { path = "../elo-lexer" }
elo-error = { path = "../elo-error" }