use crate::c;
use elo_ir::cir::{self, Program};

pub struct Generator {
    pub input: Program,
    pub body: String,
    pub head: String,
    tuples: Vec<Vec<cir::Typing>>,
    fn_types: Vec<(cir::Typing, Vec<cir::Typing>)>,
}

impl Generator {
    pub fn new(input: Program) -> Self {
        Self {
            input: input,
            body: String::new(),
            head: String::from(HEAD),
            tuples: Vec::new(),
            fn_types: Vec::new(),
        }
    }
}

const HEAD: &'static str = "// Generated by Elo compiler
// Copyright(c) 2025 Marcio Dantas, Igor Ferreira
#include <prelude.h>\n";

const MAIN: &'static str = "void __elo_main(MemoryContext* ctx)";

fn fnv_hash(text: &str) -> u32 {
    const FNV_OFFSET_BASIS_32: u32 = 2166136261;
    const FNV_PRIME_32: u32 = 16777619;
    let mut hash = FNV_OFFSET_BASIS_32;
    for byte in text.bytes() {
        hash = hash.wrapping_mul(FNV_PRIME_32);
        hash = hash ^ (byte as u32);
    }
    hash
}

fn mangle_function(name: &str) -> String {
    return format!("_fn_{name}_{}", fnv_hash(name));
}

fn mangle_enum(name: &str) -> String {
    return format!("_enum_{name}_{}", fnv_hash(name));
}

fn mangle_enum_variant(enum_name: &str, variant: &str) -> String {
    return format!("_enum_{enum_name}_{variant}_{}", fnv_hash(variant));
}

fn mangle_struct(name: &str) -> String {
    return format!("_struct_{name}_{}", fnv_hash(name));
}

fn mangle_tuple_type(no: usize) -> String {
    return format!("_tuple{no}_{}", fnv_hash(&no.to_string()));
}

fn mangle_fn_type(no: usize) -> String {
    return format!("_fn{no}_{}", fnv_hash(&no.to_string()));
}

impl Generator {
    pub fn get_fn_type(&mut self, ret: &cir::Typing, args: &Vec<cir::Typing>) -> String {
        let mut fn_type_index = None;
        for (index, fn_type) in self.fn_types.iter().enumerate() {
            if (ret, args) == (&fn_type.0, &fn_type.1) {
                fn_type_index = Some(index);
            }
        }
        if let Some(i) = fn_type_index {
            return mangle_fn_type(i);
        } else {
            let i = self.fn_types.len();
            self.fn_types.push((ret.clone(), args.clone()));
            let type_name = mangle_fn_type(i);
            let ret = self.choose_type(ret);
            let args = self.generate_fn_args(args, false);
            let fn_type = &format!("{ret}(*{type_name})({args})");
            self.head.push_str(&(c::typedef_stmt(fn_type) + "\n"));
            return type_name;
        }
    }

    pub fn get_tuple_type(&mut self, types: &Vec<cir::Typing>) -> String {
        let mut tuple_index = None;
        for (index, tuple) in self.tuples.iter().enumerate() {
            if tuple == types {
                tuple_index = Some(index);
            }
        }
        if let Some(i) = tuple_index {
            return mangle_tuple_type(i);
        } else {
            let i = self.tuples.len();
            self.tuples.push(types.clone());
            let mut body = String::new();
            for (i, j) in types.iter().enumerate() {
                body.push_str(&format!("{} t{i};\n", self.choose_type(j)));
            }
            let struct_name = mangle_tuple_type(i);
            self.head.push_str(&c::struct_stmt(&struct_name, &body));
            return struct_name;
        }
    }

    pub fn choose_type(&mut self, t: &cir::Typing) -> String {
        return match t {
            cir::Typing::Primitive(cir::Primitive::I64) => "_ELO_I64_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::I32) => "_ELO_I32_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::I16) => "_ELO_I16_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::I8) => "_ELO_I8_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::Bool) => "_ELO_BOOL_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::U64) => "_ELO_U64_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::U32) => "_ELO_U32_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::U16) => "_ELO_U16_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::U8) => "_ELO_U8_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::F32) => "_ELO_F32_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::F64) => "_ELO_F64_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::Int) => "_ELO_INT_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::UInt) => "_ELO_UINT_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::Float) => "_ELO_FLOAT_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::Str) => "_ELO_STR_T".to_string(),
            cir::Typing::Primitive(cir::Primitive::Char) => "_ELO_CHAR_T".to_string(),
            cir::Typing::Pointer { typ, mutable: _ } => self.choose_type(typ) + "*",
            cir::Typing::Array { typ, .. } => self.choose_type(typ) + "*",
            cir::Typing::Struct(cir::Struct { name, .. }) => format!("struct {}", mangle_struct(name)),
            cir::Typing::Enum(cir::Enum { name, .. }) => format!("enum {}", mangle_enum(name)),
            cir::Typing::Void => "void".to_string(),
            cir::Typing::Tuple { types } => format!("struct {}", self.get_tuple_type(types)),
            cir::Typing::Function { ret, arguments, variadic: _, extrn: _ } => {
                self.get_fn_type(ret, arguments)
            }
            _ => {
                todo!()
            }
        };
    }

    // NOTE: I'm using an option here in case of a function call that returns void,
    // which is not a valid value in LLVM unfortunately.
    // Not using the option now since we don't use LLVM anymore
    pub fn generate_expression(&mut self, expr: &cir::Expression) -> String {
        match &expr.data {
            cir::ExpressionData::Integer { value } => value.to_string(),
            cir::ExpressionData::Float { value } => value.to_string(),
            cir::ExpressionData::StringLiteral { value } => {
                // TODO: Find a way to organize this Runtime-related calls better.
                c::function_call_expr("__elo_str_new", &format!("ctx, {}", c::string_expr(value)))
            }
            cir::ExpressionData::Bool { value } => {
                return if *value { "1" } else { "0" }.to_string();
            }
            cir::ExpressionData::Cast { expr, typ } => {
                let typ = self.choose_type(typ);
                let expr = self.generate_expression(expr);
                return c::cast_expr(&expr, &typ);
            }
            cir::ExpressionData::Tuple { exprs, types } => {
                let struct_name = self.get_tuple_type(types);
                let fields = exprs
                    .iter()
                    .map(|e| self.generate_expression(e))
                    .collect::<Vec<String>>();
                return c::struct_expr_ordered(&struct_name, &fields);
            },
            cir::ExpressionData::UnaryOperation { operator, operand } => {
                let op = &self.generate_expression(operand);
                match *operator {
                    cir::UnaryOperation::Neg => c::unop_expr(op, c::Unop::Neg),
                    cir::UnaryOperation::BNot => c::unop_expr(op, c::Unop::BNot),
                    cir::UnaryOperation::Not => c::unop_expr(op, c::Unop::Not),
                    cir::UnaryOperation::Addr => c::unop_expr(op, c::Unop::Addr),
                    cir::UnaryOperation::Deref => c::unop_expr(op, c::Unop::Deref),
                }
            }
            cir::ExpressionData::BinaryOperation {
                operator,
                left,
                right,
                ..
            } => {
                let lhs = &self.generate_expression(left);
                let rhs = &self.generate_expression(right);
                match *operator {
                    cir::BinaryOperation::Add => c::binop_expr(lhs, rhs, c::Binop::Add),
                    cir::BinaryOperation::Sub => c::binop_expr(lhs, rhs, c::Binop::Sub),
                    cir::BinaryOperation::Mul => c::binop_expr(lhs, rhs, c::Binop::Mul),
                    cir::BinaryOperation::Div => c::binop_expr(lhs, rhs, c::Binop::Div),
                    cir::BinaryOperation::Mod => c::binop_expr(lhs, rhs, c::Binop::Mod),
                    cir::BinaryOperation::Eq => c::binop_expr(lhs, rhs, c::Binop::Eq),
                    cir::BinaryOperation::Ne => c::binop_expr(lhs, rhs, c::Binop::Ne),
                    cir::BinaryOperation::Lt => c::binop_expr(lhs, rhs, c::Binop::Lt),
                    cir::BinaryOperation::Le => c::binop_expr(lhs, rhs, c::Binop::Le),
                    cir::BinaryOperation::Gt => c::binop_expr(lhs, rhs, c::Binop::Gt),
                    cir::BinaryOperation::Ge => c::binop_expr(lhs, rhs, c::Binop::Ge),
                    cir::BinaryOperation::And => c::binop_expr(lhs, rhs, c::Binop::And),
                    cir::BinaryOperation::Or => c::binop_expr(lhs, rhs, c::Binop::Or),
                    cir::BinaryOperation::BAnd => c::binop_expr(lhs, rhs, c::Binop::BAnd),
                    cir::BinaryOperation::BOr => c::binop_expr(lhs, rhs, c::Binop::BOr),
                    cir::BinaryOperation::BXor => c::binop_expr(lhs, rhs, c::Binop::BXor),
                    cir::BinaryOperation::LShift => c::binop_expr(lhs, rhs, c::Binop::LShift),
                    cir::BinaryOperation::RShift => c::binop_expr(lhs, rhs, c::Binop::RShift),
                    cir::BinaryOperation::Assign => c::binop_expr(lhs, rhs, c::Binop::Assign),
                    cir::BinaryOperation::AssignAdd => c::binop_expr(lhs, rhs, c::Binop::AssignAdd),
                    cir::BinaryOperation::AssignSub => c::binop_expr(lhs, rhs, c::Binop::AssignSub),
                    cir::BinaryOperation::AssignMul => c::binop_expr(lhs, rhs, c::Binop::AssignMul),
                    cir::BinaryOperation::AssignDiv => c::binop_expr(lhs, rhs, c::Binop::AssignDiv),
                    cir::BinaryOperation::AssignMod => c::binop_expr(lhs, rhs, c::Binop::AssignMod),
                    cir::BinaryOperation::AssignBAnd => c::binop_expr(lhs, rhs, c::Binop::AssignBAnd),
                    cir::BinaryOperation::AssignBOr => c::binop_expr(lhs, rhs, c::Binop::AssignBOr),
                    cir::BinaryOperation::AssignBXor => c::binop_expr(lhs, rhs, c::Binop::AssignBXor),
                }
            }
            cir::ExpressionData::ArrayLiteral { exprs, typ } => {
                let exprs = exprs.iter().map(|e| self.generate_expression(e));
                let items = c::list(&exprs.collect::<Vec<String>>());
                let typ = self.choose_type(typ);
                return c::array_expr(&typ, &items);
            }
            cir::ExpressionData::IntrinsicCall { intrinsic, arguments } => {
                let name = match intrinsic {
                    cir::Intrinsic::Print => "__elo_print_str",
                };
                let mut real_args = vec![String::from("ctx")];
                let arguments: Vec<String> = arguments
                    .iter()
                    .map(|x| self.generate_expression(x))
                    .collect();
                real_args.extend(arguments);
                let arguments = c::list(real_args.as_slice());

                return c::function_call_expr(name, &arguments);
            }
            cir::ExpressionData::FunctionCall {
                function,
                arguments,
            } => {
                let identity = function.identity;
                let function = self.generate_expression(function);
                if let cir::ExpressionIdentity::Function(extrn) = identity {
                    let arguments = self.generate_passed_fn_args(arguments, extrn);
                    return c::function_call_expr(&function, &arguments);
                } else {
                    let arguments = self.generate_passed_fn_args(arguments, false);
                    return c::function_ptr_call_expr(&function, &arguments)
                }
            },
            cir::ExpressionData::Identifier { name } => {
                if let cir::ExpressionIdentity::Function(false) = expr.identity {
                    mangle_function(name)
                } else {
                    name.clone()
                }
            },
            cir::ExpressionData::StructInit { origin, fields } => {
                let name = origin.name.clone();
                let fields = fields
                    .iter()
                    .map(|(f, e)| (f.clone(), self.generate_expression(e)))
                    .collect::<Vec<(String, String)>>();
                let name = &mangle_struct(&name);
                return c::struct_expr(name, &fields);
            }
            cir::ExpressionData::TupleAccess { origin, field } => {
                let field = &format!("t{field}");
                return c::member_expr(&self.generate_expression(origin), field);
            },
            cir::ExpressionData::ArraySubscript { origin, index } => {
                let origin = self.generate_expression(origin);
                let index = self.generate_expression(index);
                return c::subscript_expr(&origin, &index);
            }
            cir::ExpressionData::FieldAccess { origin, field } => {
                let lhs = self.generate_expression(origin);
                let rhs = field.clone();
                return c::member_expr(&lhs, &rhs);
            }
            cir::ExpressionData::EnumVariant { origin, variant } => {
                return mangle_enum_variant(origin, variant);
            }
        }
    }

    pub fn generate_named_fn_args(&mut self, args: &Vec<(String, cir::Typing)>, extrn: bool) -> String {
        let mut result = vec![];
        if !extrn {
            result.push(c::field("MemoryContext*", "ctx"));
        }
        for (name, typ) in args {
            let t = self.choose_type(typ);
            result.push(c::field(&t, name));
        }
        return c::list(&result);
    }

    pub fn generate_fn_args(&mut self, args: &Vec<cir::Typing>, extrn: bool) -> String {
        let mut result = vec![];
        if !extrn {
            result.push(String::from("MemoryContext*"));
        }
        for typ in args {
            let t = self.choose_type(typ);
            result.push(t);
        }
        return c::list(&result);
    }

    pub fn generate_passed_fn_args(&mut self, args: &Vec<cir::Expression>, extrn: bool) -> String {
        let mut result = vec![];
        if !extrn {
            result.push(String::from("ctx"));
        }
        for expr in args {
            let e = self.generate_expression(expr);
            result.push(e);
        }
        return c::list(&result);
    }

    pub fn generate_statement(&mut self, stmt: &mut cir::Statement) -> String {
        let mut output = String::new();
        match &mut stmt.kind {
            cir::StatementKind::Constant {
                value,
                binding,
                typing,
            } => {
                self.head.push_str("static const ");
                let x = self.choose_type(typing);
                self.head.push_str(x.as_str());
                self.head.push_str(&binding);
                self.head.push('=');
                let expr = self.generate_expression(&value);
                self.head.push_str(&expr);
                self.head.push_str(";\n");
            }
            cir::StatementKind::FnStatement(stmt) => {
                let body = stmt
                    .block
                    .iter_mut()
                    .map(|x| self.generate_statement(x))
                    .collect::<Vec<String>>();
                let body = c::statement_list(body.as_slice());

                if stmt.head.name == "main" {
                    output.push_str(&c::function_sign(
                        MAIN,
                        &body,
                    ));
                    return output;
                }

                let r#return = self.choose_type(&stmt.head.ret);
                let name = stmt.head.name.clone();
                let arguments = self.generate_named_fn_args(&stmt.head.arguments, stmt.head.extrn);
                let name = &mangle_function(&name);
                self.head.push_str(&c::function_decl_stmt(&r#return, name, &arguments, false));
                output.push_str(&c::function_stmt(
                    &r#return,
                    name,
                    &arguments,
                    stmt.head.variadic,
                    &body,
                ));
            }
            cir::StatementKind::ExternFnStatement(stmt) => {
                let r#return = self.choose_type(&stmt.ret);
                let name = stmt.name.clone();
                let arguments = self.generate_named_fn_args(&stmt.arguments, true);
                self.head.push_str(&c::function_decl_stmt(
                    &r#return,
                    &name,
                    &arguments,
                    stmt.variadic,
                ));
            }
            cir::StatementKind::StructStatement(stmt) => {
                let fields = stmt
                    .fields
                    .iter()
                    .map(|(k, v)| c::struct_field(&self.choose_type(v), k));
                let fields = fields.collect::<Vec<String>>();
                let body = c::statement_list(&fields);
                self.head.push_str(&c::struct_stmt(&mangle_struct(&stmt.name), &body));
            }
            cir::StatementKind::EnumStatement(stmt) => {
                let vars: Vec<String> = stmt.variants.iter().map(|x| mangle_enum_variant(&stmt.name, x)).collect();
                let doby = c::list(&vars);
                self.head.push_str(&c::enum_stmt(&mangle_enum(&stmt.name), &doby));
            }
            // BODY STATEMENTS //
            cir::StatementKind::Variable {
                binding,
                assignment,
                typing,
                ..
            } => {
                let typ = self.choose_type(typing);
                let expr = self.generate_expression(&assignment);
                output.push_str(&c::variable_stmt(&typ, binding, &expr));
            }
            cir::StatementKind::ExpressionStatement(expr) => {
                let e = self.generate_expression(&expr);
                output.push_str(&c::expr_stmt(&e));
            }
            cir::StatementKind::ReturnStatement { value, .. } => {
                let e = value.as_ref().map(|x| self.generate_expression(x));
                output.push_str(&c::return_stmt(e));
            }
            cir::StatementKind::IfStatement {
                condition,
                block_true,
                block_false,
                ..
            } => {
                let comparison = self.generate_expression(&condition);
                let r#true = block_true
                    .iter_mut()
                    .map(|x| self.generate_statement(x))
                    .collect::<Vec<String>>();
                let r#true = c::statement_list(r#true.as_slice());

                let mut r#false = None;
                if !block_false.is_empty() {
                    let f = block_false
                        .iter_mut()
                        .map(|x| self.generate_statement(x))
                        .collect::<Vec<String>>();
                    r#false = Some(c::statement_list(f.as_slice()));
                }
                output.push_str(&c::if_stmt(&comparison, &r#true, r#false));
            }
            cir::StatementKind::WhileStatement { condition, block } => {
                let comparison = self.generate_expression(&condition);
                let block = block
                    .iter_mut()
                    .map(|x| self.generate_statement(x))
                    .collect::<Vec<String>>();
                let block = c::statement_list(block.as_slice());
                output.push_str(&c::while_stmt(&comparison, &block));
            }
        };
        return output;
    }

    pub fn go(&mut self) {
        for mut node in std::mem::take(&mut self.input.nodes) {
            let out = &self.generate_statement(&mut node);
            self.body.push_str(out);
        }
    }
}
